name: Run Unit Tests

on:
  push:
    branches: 
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Run Checkout Dev 
    - uses: borales/actions-yarn@v2.0.0
      name: Run Install
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.0.0
      name: Run Build
      with:
        cmd: build # will run `yarn build` command
    - uses: borales/actions-yarn@v2.0.0
      name: Run Test
      with:
        cmd: test --ci --forceExit # will run `yarn test` command
    - name: Run Checkout Mester and Rebase Dev
      run: |
        git status
        git checkout master
        git rebase dev
      env:
        CI: true
