name: Run Unit Tests

on:
  push:
    branches: 
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Run Checkout Dev 
    - name: Run Install
      run: yarn install
    - name: Run Build
      run: yarn build
    - name: Run Test
      run: yarn test
    - name: Run Checkout Mester and Rebase Dev
      run: |
        git status
        git checkout master
        git rebase dev
      env:
        CI: true
